[tool.poetry]
name = "kosmosx"
version = "0.3.1"
description = "Transformers at zeta scales"
authors = ["Zeta Team <kye@apac.ai>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kyegomez/Kosmos-X"
keywords = ["Transformers", "zeta scale"]
classifiers = [
    "Programming Language :: Python :: 3",
]
[tool.poetry.dependencies]
python = "^3.8"
torch = "2.1.1"
fairscale = "0.4.0"
timm = "0.6.13"
torchdiffeq = "0.2.3"
pytest = "7.4.2"
einops = "0.7.0"
bitsandbytes = "0.38.1"
typing = "3.7.4.3"
transformers = "4.35.0"
einops-exts = "0.0.4"
torchvision = "0.16.1"
accelerate = "0.22.0"
datasets = "2.10.1"
lion-pytorch = "0.0.7"
sentencepiece = "0.1.98"
colt5-attention = "0.10.19"
vector-quantize-pytorch = "1.12.0"
tokenmonster = "1.1.12"
scipy = "1.9.3"
beartype = "0.15.0"
tiktoken = "0.4.0"
tqdm = "4.66.1"
zetascale = "*"
rich = "13.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
ruff = ">=0.0.249,<0.1.8"
types-toml = "^0.10.8.1"
types-redis = "^4.3.21.6"
types-pytz = "^2023.3.0.0"
black = "^23.1.0"
types-chardet = "^5.0.4.6"
mypy-protobuf = "^3.0.0"


[tool.autopep8]
max_line_length = 80
ignore = "E501,W6"  # or ["E501", "W6"]
in-place = true
recursive = true
aggressive = 3

[tool.ruff]
line-length = 80

[tool.black]
line-length = 80
target-version = ['py38']
preview = true







